"""
Pydantic schemas used for request validation and response serialization.
"""
import datetime
from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, EmailStr, Field, field_validator

from app.config import settings

# ---------------------------------------------------------------------------
# Auth / User
# ---------------------------------------------------------------------------


class UserCreate(BaseModel):
    username: str = Field(..., min_length=3, max_length=64)
    email: EmailStr
    password: str = Field(..., min_length=6, max_length=128)
    full_name: Optional[str] = Field(None, max_length=128)


class UserOut(BaseModel):
    id: int
    username: str
    email: EmailStr
    full_name: Optional[str] = None
    is_active: bool
    created_at: datetime.datetime

    class Config:
        from_attributes = True


class Token(BaseModel):
    access_token: str
    token_type: str = "bearer"


class TokenData(BaseModel):
    username: Optional[str] = None


# ---------------------------------------------------------------------------
# Device
# ---------------------------------------------------------------------------


class DeviceCreate(BaseModel):
    device_id: Optional[str] = Field(
        None,
        max_length=64,
        description="The physical ID printed/burned onto the hardware. "
        "If omitted, a new unique ID is generated by the server.",
    )
    name: Optional[str] = Field(None, max_length=128, description="Friendly name for the device")


class DeviceOut(BaseModel):
    device_id: str
    name: Optional[str] = None
    is_active: bool
    created_at: datetime.datetime
    last_seen_at: Optional[datetime.datetime] = None

    class Config:
        from_attributes = True


class DeviceCreatedOut(DeviceOut):
    """Returned only once at creation / secret-regeneration time."""

    device_secret: str = Field(
        ..., description="Secret the hardware must present to open a websocket connection. Store it safely."
    )


class DeviceUpdate(BaseModel):
    name: Optional[str] = Field(None, max_length=128)
    is_active: Optional[bool] = None


# ---------------------------------------------------------------------------
# Sensor data
# ---------------------------------------------------------------------------


class SensorDataIn(BaseModel):
    """Payload the hardware sends over the websocket for each sample."""

    body_temperature: float
    heart_rate: float
    spo2: float
    heart_beat_height: float
    timestamp: Optional[datetime.datetime] = None

    @field_validator("heart_rate")
    @classmethod
    def check_heart_rate(cls, v):
        if not (settings.HEART_RATE_MIN <= v <= settings.HEART_RATE_MAX):
            raise ValueError(
                f"heart_rate must be between {settings.HEART_RATE_MIN} and {settings.HEART_RATE_MAX}"
            )
        return v

    @field_validator("spo2")
    @classmethod
    def check_spo2(cls, v):
        if not (settings.SPO2_MIN <= v <= settings.SPO2_MAX):
            raise ValueError(f"spo2 must be between {settings.SPO2_MIN} and {settings.SPO2_MAX}")
        return v

    @field_validator("body_temperature")
    @classmethod
    def check_body_temperature(cls, v):
        if not (settings.BODY_TEMP_MIN <= v <= settings.BODY_TEMP_MAX):
            raise ValueError(
                f"body_temperature must be between {settings.BODY_TEMP_MIN} and {settings.BODY_TEMP_MAX}"
            )
        return v


class SensorReadingOut(BaseModel):
    id: int
    body_temperature: float
    heart_rate: float
    spo2: float
    heart_beat_height: float
    recorded_at: datetime.datetime

    class Config:
        from_attributes = True


class ReadingsJSONResponse(BaseModel):
    device_id: str
    count: int
    start: Optional[datetime.datetime] = None
    end: Optional[datetime.datetime] = None
    limit: int
    offset: int
    order: str
    readings: List[SensorReadingOut]


# ---------------------------------------------------------------------------
# AI Review
# ---------------------------------------------------------------------------


class AIReviewRequest(BaseModel):
    start: Optional[datetime.datetime] = Field(
        None, description="Start of the data range to analyze. Defaults to 24h before `end`."
    )
    end: Optional[datetime.datetime] = Field(
        None, description="End of the data range to analyze. Defaults to now."
    )
    limit_samples: Optional[int] = Field(
        None, description="Optional cap on number of most-recent samples analyzed within the range."
    )


class AIReviewOut(BaseModel):
    id: int
    device_id: str
    created_at: datetime.datetime
    range_start: Optional[datetime.datetime] = None
    range_end: Optional[datetime.datetime] = None
    samples_analyzed: int
    apnea_detected: bool
    risk_score: float
    confidence: float
    summary: Optional[str] = None
    model_version: str
    details: Optional[Dict[str, Any]] = None

    class Config:
        from_attributes = True


# ---------------------------------------------------------------------------
# WebSocket outgoing message envelope (frontend live-stream)
# ---------------------------------------------------------------------------


class WSReadingMessage(BaseModel):
    type: Literal["reading"] = "reading"
    device_id: str
    data: SensorReadingOut
